AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ExecutionOfInterest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 3008

Resources:
  ExecutionOfInterestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        ExecutionOfInterest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExecutionOfInterestApi:
    Description: "API Gateway endpoint URL for ExecutionOfInterest function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ExecutionOfInterest/"
  ExecutionOfInterestFunction:
    Description: "ExecutionOfInterest Lambda Function ARN"
    Value: !GetAtt ExecutionOfInterestFunction.Arn
  ExecutionOfInterestFunctionIamRole:
    Description: "Implicit IAM Role created for ExecutionOfInterest function"
    Value: !GetAtt ExecutionOfInterestFunctionRole.Arn
